// Permissões do sistema. Cada perfil de usuário declara as suas.
const Permissao = Object.freeze({
  GERENCIAR_CADASTROS: 'GERENCIAR_CADASTROS',
  GERENCIAR_BIMESTRES: 'GERENCIAR_BIMESTRES',
  REVISAR_ACOMPANHAMENTO: 'REVISAR_ACOMPANHAMENTO',
  REGISTRAR_ACOMPANHAMENTO: 'REGISTRAR_ACOMPANHAMENTO',
  CONSULTAR_HISTORICO: 'CONSULTAR_HISTORICO',
  VER_RELATORIOS_PUBLICADOS: 'VER_RELATORIOS_PUBLICADOS',
});

module.exports = Permissao;
