CREATE TABLE CURSO (
    CURS_CODIGO NUMBER(3) PRIMARY KEY,
    CURS_NOME VARCHAR2(200) NOT NULL,
    CURS_DESCRICAO VARCHAR2(2000) NOT NULL
);

CREATE TABLE PLANO (
    PLAN_CODIGO NUMBER(3) PRIMARY KEY,
    PLAN_VALOR_TOTAL NUMBER(7,2) NOT NULL,
    PLAN_DATA_INCLUSAO DATE NOT NULL,
    PLAN_DATA_VALIDADE DATE NOT NULL
);

CREATE TABLE TURMA (
    TURM_CODIGO NUMBER(3) PRIMARY KEY,
    TURM_NOME VARCHAR2(50) NOT NULL
);

CREATE TABLE DISCIPLINA (
    DISC_CODIGO NUMBER(3) PRIMARY KEY,
    DISC_NOME VARCHAR2(200) NOT NULL,
    DISC_CARGA_HORARIA NUMBER(3) NOT NULL
);

CREATE TABLE ALUNO (
    ALUN_RA NUMBER(5) PRIMARY KEY, 
	ALUN_NOME VARCHAR2(200) NOT NULL, 
	ALUN_CPF VARCHAR2(11) NOT NULL, 
	ALUN_DATA_NASCIMENTO DATE NOT NULL, 
	ALUN_LOGR_CEP VARCHAR2(8), 
	ALUN_NUMERO VARCHAR2(6), 
	ALUN_COMPLEMENTO VARCHAR2(30)
);

CREATE TABLE GRADE (
    GRAD_CODIGO NUMBER(3) PRIMARY KEY,
    GRAD_PROF_CODIGO NUMBER(3) NOT NULL,
    GRAD_DISC_CODIGO NUMBER(3) NOT NULL,
    GRAD_CTUR_CODIGO NUMBER(3) NOT NULL
);

CREATE TABLE CURSO_PLANO (
    CPLA_CODIGO NUMBER(3) PRIMARY KEY,
    CPLA_CURS_CODIGO NUMBER(3) NOT NULL,
    CPLA_PLAN_CODIGO NUMBER(3) NOT NULL
);

CREATE TABLE PROFESSOR (
    PROF_CODIGO NUMBER(3) PRIMARY KEY,
    PROF_NOME VARCHAR2(200) NOT NULL
);

CREATE TABLE CURSO_TURMA (
    CTUR_CURS_CODIGO NUMBER(3) NOT NULL,
    CTUR_TURM_CODIGO NUMBER(3) NOT NULL,
    CTUR_CODIGO NUMBER(3) PRIMARY KEY
);

CREATE TABLE CURSO_ALUNO (
    CALU_CPLA_CODIGO NUMBER(3) NOT NULL,
    CALU_ALUN_RA NUMBER(5) NOT NULL
);

CREATE TABLE ALUNO_GRADE (
    ALUG_GRAD_CODIGO NUMBER(3) NOT NULL,
    ALUG_ALUN_RA NUMBER(5) NOT NULL,
    ALUG_NOTA NUMBER(3,1),
    ALUG_FALTA NUMBER(2),
    ALUG_DATA DATE
);

CREATE TABLE ALUNO_CONTATO (
    ALCO_CODIGO NUMBER(9) PRIMARY KEY,
    ALCO_ALUN_RA NUMBER(8) NOT NULL,
    ALCO_CONTATO VARCHAR2(50) NOT NULL,
    ALCO_TIPO VARCHAR2(20) NOT NULL
);

CREATE TABLE LOGRADOURO (
    LOGR_CEP VARCHAR2(8) NOT NULL PRIMARY KEY,
    LOGR_LOGRADOURO VARCHAR2(200) NOT NULL,
    LOGR_BAIRRO VARCHAR2(100) NOT NULL,
    LOGR_CIDADE VARCHAR2(100) NOT NULL,
    LOGR_ESTADO VARCHAR2(5) NOT NULL,
    LOGR_PAIS VARCHAR2(100) NOT NULL
);

ALTER TABLE GRADE ADD CONSTRAINT FK_GRADE_1
    FOREIGN KEY (GRAD_PROF_CODIGO)
    REFERENCES PROFESSOR (PROF_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE GRADE ADD CONSTRAINT FK_GRADE_2
    FOREIGN KEY (GRAD_DISC_CODIGO)
    REFERENCES DISCIPLINA (DISC_CODIGO);
 
ALTER TABLE GRADE ADD CONSTRAINT FK_GRADE_3
    FOREIGN KEY (GRAD_CTUR_CODIGO)
    REFERENCES CURSO_TURMA (CTUR_CODIGO);
 
ALTER TABLE CURSO_PLANO ADD CONSTRAINT FK_CURSO_PLANO_1
    FOREIGN KEY (CPLA_CURS_CODIGO)
    REFERENCES CURSO (CURS_CODIGO);
 
ALTER TABLE CURSO_PLANO ADD CONSTRAINT FK_CURSO_PLANO_2
    FOREIGN KEY (CPLA_PLAN_CODIGO)
    REFERENCES PLANO (PLAN_CODIGO);
 
ALTER TABLE CURSO_TURMA ADD CONSTRAINT FK_CURSO_TURMA_1
    FOREIGN KEY (CTUR_CURS_CODIGO)
    REFERENCES CURSO (CURS_CODIGO);
 
ALTER TABLE CURSO_TURMA ADD CONSTRAINT FK_CURSO_TURMA_2
    FOREIGN KEY (CTUR_TURM_CODIGO)
    REFERENCES TURMA (TURM_CODIGO)
    ON DELETE SET NULL;
 
ALTER TABLE CURSO_ALUNO ADD CONSTRAINT FK_CURSO_ALUNO_1
    FOREIGN KEY (CALU_CPLA_CODIGO)
    REFERENCES CURSO_PLANO (CPLA_CODIGO);
 
ALTER TABLE CURSO_ALUNO ADD CONSTRAINT FK_CURSO_ALUNO_2
    FOREIGN KEY (CALU_ALUN_RA)
    REFERENCES ALUNO (ALUN_RA);
 
ALTER TABLE ALUNO_GRADE ADD CONSTRAINT FK_ALUNO_GRADE_1
    FOREIGN KEY (ALUG_GRAD_CODIGO)
    REFERENCES GRADE (GRAD_CODIGO);
 
ALTER TABLE ALUNO_GRADE ADD CONSTRAINT FK_ALUNO_GRADE_2
    FOREIGN KEY (ALUG_ALUN_RA)
    REFERENCES ALUNO (ALUN_RA)
    ON DELETE SET NULL;
    
ALTER TABLE ALUNO_CONTATO ADD CONSTRAINT FK_ALUNO_CONTATO_1
    FOREIGN KEY (ALCO_ALUN_RA)
    REFERENCES ALUNO (ALUN_RA);
    
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_1
    FOREIGN KEY (ALUN_LOGR_CEP)
    REFERENCES LOGRADOURO (LOGR_CEP);    
    
    
